server:
  port: 3997

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - 'http://localhost:3000'
              - 'https://pintech.koreait.xyz'

        allowCredentials: true # 요청시 인증정보 전송 허가
        allowedHeaders: '*'
        allowedMethods: '*'
      discovery.locator:
        enabled: true # 유레카서버에서 찾는 여부
        lowerCaseServiceId: true # 소문자로 주소 완성
      routes:
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/api/v1/member/** # 실제 접근 경로
          filters:
            - RewritePath=/api/v1/member/?(?<path>.*),/$\{path}
        - id: pokemon-service
          uri: lb://pokemon-service
          predicates:
            - Path=/api/v1/pokemon/** # 실제 접근 경로
          filters:
            - RewritePath=/api/v1/pokemon/?(?<path>.*),/$\{path}

# 유레카 설정
eureka:
  instance:
    hostname: ${hostname}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${eureka.server}/eureka/

# 액츄에이터 설정
management:
  endpoint:
    gateway:
      enabled: true

  endpoints:
    web:
      exposure:
        include: gateway