spring:
  # redis 설정 - Session 공간 분리
  data:
    redis:
      host: localhost
      port: 6379

  # DB 설정
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    hibernate:
      ddlAuto: update

# File Upload 경로
file:
  # upload.path: E:/[uploads]/
  # upload.path: D:/uploads/
  upload.path: C:/Users/admin/Desktop/resource/uploads/
  upload.url: /uploads/